version: '3.1'

services:
  pg_db:
    image: postgres:14.6
    env_file:
      - .env
    volumes:
      - /docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  web:
    image: stepzat/parser_web:0.5
    depends_on:
      - pg_db
    volumes:
      - static:/usr/src/parserapp/static
    env_file:
      - .env
    expose:
      - "8000"

  nginx:
    image: stepzat/parser_nginx:0.5
    depends_on:
      - web
    volumes:
      - static:/static
    ports:
      - "80:80"


volumes:
  static:
